IdeaNote:
  metadata_file: ideanote.json
  sync:
    remote:
      method: github
      connection:
        owner: bmark-sync
        email: thankall@yeah.net
        repo: test_github_api
        access_token: af9a3e3b83b72faa89c56846c50b20e921030b6d
        branch: master

  note_data_path: E:\\MyNote
  log_dir: log



