IdeaNote:
  port: 5555
  hide_window: False
  auth_code: 123456
  sync:
    method: github
    connection:
      owner: xxxxxx
      email: 123456@xxx.yyy
      repo: xxxxxx
      access_token: 20a50aaxxxxxxxxxxxxxxxxxxd21781
      branch: master
    work_dir: D:\ideanote_sync
  db:
    config:
      SQLALCHEMY_ECHO: False
      CREATE_DB_IF_NOT_FOUND: True
      JSON_AS_ASCII: False
      SECRET_KEY: '123456789'
      SQLALCHEMY_DATABASE_URI: sqlite:///ideanote.db?check_same_thread=False
      SQLALCHEMY_TRACK_MODIFICATIONS: False
  log:
    directory: D:\log
    formatter: "%(asctime)s %(levelname)s %(filename)s %(lineno)d: %(message)s"
  urlmark:
    sync: True
    sync_file: D:\ideanote_sync\chrome_bookmark.json